name: Java BDD Test Automation Framework CI Build

on:
  push:
    branches:
      - master
      - feature/*
  pull_request:
    branches:
      - master
      - feature/*

permissions:
  contents: write
  checks: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'
          java-version: '11'

      # Cache Maven dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v4.1.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Build the project
      - name: Build Project
        run: |
          mvn clean install

  test:
    runs-on: windows-latest
    needs: build # Ensure tests only run after a successful build

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'
          java-version: '11'

      # Run Tests
      - name: Run Tests
        run: |
          mvn test

      # Archive Test Reports
      - name: Archive Test Reports
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: cucumber-reports
          path: target/cucumber-reports/*.html

      # Publish JUnit Test Results
      - name: Publish Test Results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Java BDD Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: false
